/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifes.poo1.CIH;

import br.edu.ifes.poo1.CDP.Tabuleiro;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author heitor.coelho
 */
public class Promocao extends javax.swing.JFrame {

    /**
     * Creates new form Promocao
     */
    String caminho = System.getProperty("user.dir") + "\\src\\main\\java\\br\\edu\\ifes\\poo1\\Imagens\\";
    Image tp = this.getToolkit().createImage(caminho + "torrepreta.png");
    Image cp = this.getToolkit().createImage(caminho + "cavalopreto.png");
    Image bp = this.getToolkit().createImage(caminho + "bispopreto.png");
    Image qp = this.getToolkit().createImage(caminho + "rainhapreta.png");
    private String posicao;
    private boolean vezBranco;
    private Tabuleiro tabuleiro;
    private Visual tela;
    
    public Promocao(Visual tela) {
        initComponents();
        lbl_bispo.setIcon(new ImageIcon(bp));
        lbl_cavalo.setIcon(new ImageIcon(cp));
        lbl_rainha.setIcon(new ImageIcon(qp));
        lbl_torre.setIcon(new ImageIcon(tp));
        this.tela= tela;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_torre = new javax.swing.JLabel();
        lbl_cavalo = new javax.swing.JLabel();
        lbl_bispo = new javax.swing.JLabel();
        lbl_rainha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_torre.setBackground(new java.awt.Color(204, 204, 204));
        lbl_torre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_torre.setOpaque(true);
        lbl_torre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_torreMouseClicked(evt);
            }
        });

        lbl_cavalo.setBackground(new java.awt.Color(204, 204, 204));
        lbl_cavalo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cavalo.setOpaque(true);
        lbl_cavalo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cavaloMouseClicked(evt);
            }
        });

        lbl_bispo.setBackground(new java.awt.Color(204, 204, 204));
        lbl_bispo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bispo.setOpaque(true);
        lbl_bispo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_bispoMouseClicked(evt);
            }
        });

        lbl_rainha.setBackground(new java.awt.Color(204, 204, 204));
        lbl_rainha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rainha.setMaximumSize(new java.awt.Dimension(60, 60));
        lbl_rainha.setMinimumSize(new java.awt.Dimension(60, 60));
        lbl_rainha.setOpaque(true);
        lbl_rainha.setPreferredSize(new java.awt.Dimension(60, 60));
        lbl_rainha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_rainhaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Clique na peça escolhida para a Promoção do Peão:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_rainha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lbl_bispo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lbl_cavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(lbl_torre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rainha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bispo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cavalo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_torre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 180));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_rainhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_rainhaMouseClicked
        tabuleiro.promovePeca('1', posicao, vezBranco);
        this.setVisible(false);
        tela.atualizaTabuleiro();
    }//GEN-LAST:event_lbl_rainhaMouseClicked

    private void lbl_bispoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bispoMouseClicked
        tabuleiro.promovePeca('2', posicao, vezBranco);
        tela.atualizaTabuleiro();
        this.setVisible(false);
    }//GEN-LAST:event_lbl_bispoMouseClicked

    private void lbl_cavaloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cavaloMouseClicked
        tabuleiro.promovePeca('3', posicao, vezBranco);
        tela.atualizaTabuleiro();
        this.setVisible(false);
    }//GEN-LAST:event_lbl_cavaloMouseClicked

    private void lbl_torreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_torreMouseClicked
        tabuleiro.promovePeca('3', posicao, vezBranco);
        tela.atualizaTabuleiro();
        this.setVisible(false);
        
    }//GEN-LAST:event_lbl_torreMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bispo;
    private javax.swing.JLabel lbl_cavalo;
    private javax.swing.JLabel lbl_rainha;
    private javax.swing.JLabel lbl_torre;
    // End of variables declaration//GEN-END:variables

    public void atualizaPromocao(Tabuleiro tabuleiro, String posicao, boolean vezBranco) {
        this.tabuleiro = tabuleiro;
        this.posicao = posicao;
        this.vezBranco = vezBranco;
    }
}
