/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifes.poo1.CIH;

import br.edu.ifes.poo1.CCI.ControleTotal;
import br.edu.ifes.poo1.CDP.Tabuleiro;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author heitor.coelho
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    String caminho = System.getProperty("user.dir") + "\\src\\main\\java\\br\\edu\\ifes\\poo1\\Imagens\\";
    Image tp = this.getToolkit().createImage(caminho + "torrepreta.png");
    Image cp = this.getToolkit().createImage(caminho + "cavalopreto.png");
    Image bp = this.getToolkit().createImage(caminho + "bispopreto.png");
    Image qp = this.getToolkit().createImage(caminho + "rainhapreta.png");
    Image kp = this.getToolkit().createImage(caminho + "reipreto.png");
    Image pp = this.getToolkit().createImage(caminho + "peaopreto.png");
    Image tb = this.getToolkit().createImage(caminho + "torrebranca.png");
    Image cb = this.getToolkit().createImage(caminho + "cavalobranco.png");
    Image bb = this.getToolkit().createImage(caminho + "bispobranco.png");
    Image qb = this.getToolkit().createImage(caminho + "rainhabranca.png");
    Image kb = this.getToolkit().createImage(caminho + "reibrancoo.png");
    Image pb = this.getToolkit().createImage(caminho + "peaobranco.png");
    
    Tabuleiro tabuleiro = new Tabuleiro();
    ControleTotal control = new ControleTotal(tabuleiro);

    public Visual() {
        
        initComponents();
        iniciandoTabuleiro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_11 = new javax.swing.JLabel();
        lbl_l_1 = new javax.swing.JLabel();
        lbl_l_2 = new javax.swing.JLabel();
        lbl_12 = new javax.swing.JLabel();
        lbl_14 = new javax.swing.JLabel();
        lbl_13 = new javax.swing.JLabel();
        lbl_15 = new javax.swing.JLabel();
        lbl_16 = new javax.swing.JLabel();
        lbl_17 = new javax.swing.JLabel();
        lbl_18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_digitecomando = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_vez = new javax.swing.JLabel();
        lbl_jogador1 = new javax.swing.JLabel();
        lbl_jogador2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_11.setBackground(new java.awt.Color(0, 0, 0));
        lbl_11.setForeground(new java.awt.Color(255, 255, 255));
        lbl_11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_11.setText("11");
        lbl_11.setToolTipText("");
        lbl_11.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        lbl_11.setFocusable(false);
        lbl_11.setOpaque(true);
        jPanel1.add(lbl_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 70));

        lbl_l_1.setText("1");
        jPanel1.add(lbl_l_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lbl_l_2.setText("2");
        jPanel1.add(lbl_l_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lbl_12.setBackground(new java.awt.Color(255, 255, 255));
        lbl_12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_12.setText("12");
        lbl_12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_12.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        lbl_12.setFocusable(false);
        lbl_12.setOpaque(true);
        jPanel1.add(lbl_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 70, 70));

        lbl_14.setBackground(new java.awt.Color(255, 255, 255));
        lbl_14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_14.setText("14");
        lbl_14.setFocusable(false);
        lbl_14.setOpaque(true);
        jPanel1.add(lbl_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 70, 70));

        lbl_13.setBackground(new java.awt.Color(0, 0, 0));
        lbl_13.setForeground(new java.awt.Color(255, 255, 255));
        lbl_13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_13.setText("13");
        lbl_13.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        lbl_13.setFocusable(false);
        lbl_13.setOpaque(true);
        jPanel1.add(lbl_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 70, 70));

        lbl_15.setBackground(new java.awt.Color(0, 0, 0));
        lbl_15.setForeground(new java.awt.Color(255, 255, 255));
        lbl_15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_15.setText("15");
        lbl_15.setFocusable(false);
        lbl_15.setOpaque(true);
        jPanel1.add(lbl_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 70, 70));

        lbl_16.setBackground(new java.awt.Color(255, 255, 255));
        lbl_16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_16.setText("16");
        lbl_16.setFocusable(false);
        lbl_16.setOpaque(true);
        jPanel1.add(lbl_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 70, 70));

        lbl_17.setBackground(new java.awt.Color(0, 0, 0));
        lbl_17.setForeground(new java.awt.Color(255, 255, 255));
        lbl_17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_17.setText("17");
        lbl_17.setFocusable(false);
        lbl_17.setOpaque(true);
        jPanel1.add(lbl_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 70, 70));

        lbl_18.setBackground(new java.awt.Color(255, 255, 255));
        lbl_18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_18.setText("18");
        lbl_18.setFocusable(false);
        lbl_18.setOpaque(true);
        jPanel1.add(lbl_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 70, 70));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lbl_digitecomando.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_digitecomando.setForeground(new java.awt.Color(255, 255, 255));
        lbl_digitecomando.setText("Digite o Comando:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Realizar Jogada");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_digitecomando)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_digitecomando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        lbl_vez.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_vez.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_vez.setText("VEZ BRANCO");

        lbl_jogador1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_jogador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jogador1.setText("jLabel1");
        lbl_jogador1.setOpaque(true);

        lbl_jogador2.setBackground(new java.awt.Color(0, 0, 0));
        lbl_jogador2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_jogador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_jogador2.setText("jLabel2");
        lbl_jogador2.setOpaque(true);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("x");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_jogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_jogador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lbl_vez, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_vez, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_jogador1)
                    .addComponent(lbl_jogador2)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1)
                        .addGap(49, 49, 49))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(jButton1)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        lbl_11.setIcon(new ImageIcon(bp));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_11;
    private javax.swing.JLabel lbl_12;
    private javax.swing.JLabel lbl_13;
    private javax.swing.JLabel lbl_14;
    private javax.swing.JLabel lbl_15;
    private javax.swing.JLabel lbl_16;
    private javax.swing.JLabel lbl_17;
    private javax.swing.JLabel lbl_18;
    private javax.swing.JLabel lbl_digitecomando;
    private javax.swing.JLabel lbl_jogador1;
    private javax.swing.JLabel lbl_jogador2;
    private javax.swing.JLabel lbl_l_1;
    private javax.swing.JLabel lbl_l_2;
    private javax.swing.JLabel lbl_vez;
    // End of variables declaration//GEN-END:variables

    private void iniciandoTabuleiro() {
        retiraNomeLbl();
        lbl_11.setIcon(new ImageIcon(tb));
        lbl_12.setIcon(new ImageIcon(cb));
        lbl_13.setIcon(new ImageIcon(bb));
        lbl_14.setIcon(new ImageIcon(qb));
        lbl_15.setIcon(new ImageIcon(kb));
        lbl_jogador1.setText("TESTE");
        //lbl_jogador1.setText(JOptionPane.showInputDialog("Digite nome do Jogador 1:").toUpperCase());
       // lbl_jogador1.setText(JOptionPane.showInputDialog("Digite nome do Jogador 1:").toUpperCase());
       // lbl_jogador2.setText(JOptionPane.showInputDialog("Digite nome do Jogador 2:").toUpperCase());
        //control.processaJogadorVisual(lbl_jogador1.getText(),lbl_jogador2.getText());
        

    }

    public ImageIcon criarImageIcon(String caminho, String descricao) {
        java.net.URL imgURL = getClass().getResource(caminho);
        if (imgURL != null) {
            return new ImageIcon(imgURL, descricao);
        } else {
            System.err.println("Não foi possível carregar o arquivo de imagem: " + caminho);
            return null;
        }
    }

    private void atualizaTabuleiro(){
        
        control.processaJogador();
    }
    
    private void retiraNomeLbl(){
        lbl_11.setText("");
        lbl_12.setText("");
        lbl_13.setText("");
        lbl_14.setText("");
        lbl_15.setText("");
        lbl_16.setText("");
        lbl_17.setText("");
        lbl_18.setText("");
    }
            
    
    
    
}//fimVISUAL
